services:
  App\ElasticRepository\ArtistElasticRepository:
    arguments:
      - '@fos_elastica.finder.app.artist'

  App\ElasticRepository\EventElasticRepository:
    arguments:
      - '@fos_elastica.finder.app.event'

  App\ElasticRepository\LocationElasticRepository:
    arguments:
      - '@fos_elastica.finder.app.location'