# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    body_listener: true
    routing_loader:
        include_format: false
    serializer:
        serialize_null: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
        default_format: json
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }

    #routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
