# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
  clients:
    default: { host: '%env(ELASTIC_HOST)%', port: '%env(ELASTIC_PORT)%' }
  indexes:
    app:
      client: default
      settings:
        index:
          analysis:
            tokenizer:
              my_tokenizer:
                type: "edge_ngram"
                min_gram: 1
                max_gram: 12
                token_chars:
                  - 'letter'
                  - 'digit'
            analyzer:
              my_analyzer:
                tokenizer: "my_tokenizer"
                filter: [ "lowercase" ]
      types:
        artist:
          properties:
            id:
              type: "integer"
            name:
              type: "text"
              analyzer: my_analyzer
            validated:
              type: "boolean"
            events:
              type: "nested"
              properties:
                id:
                  type: "integer"
                name:
                  type: "text"
          persistence:
            driver: orm
            model: App\Entity\Artist
            provider: ~
            listener: ~
            finder: ~
