# docker-compose.yml
version: '3'

services:
  db:
    image: mariadb:10.3.6
    volumes:
      - ${STORAGE_PATH}/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  elastic:
    image: elasticsearch:5
    ports:
      - 9200:9200
    volumes:
      - ${STORAGE_PATH}/elastic:/usr/share/elasticsearch/data

  app:
    build: .
    env_file: .env
    links:
      - db
      - elastic
      - scrapper
    volumes:
      - ./Docker/php/www.prod.conf:/etc/php/7.1/fpm/pool.d/www.conf:ro
      - .:/var/app

  nginx:
    image: nginx:1.13
    ports:
      - 8090:80
    links:
      - app
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/

  scrapper:
    image: deuxmax/concerto-scrapper:0.0.1
    ports:
      - 8090:8090
    links:
      - nginx
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CONCERTO_URL: 'http://nginx/api'

  redis:
    image: redis:3.2
    volumes:
      - ${STORAGE_PATH}/redis:/data