# docker-compose.yml
version: '3'

volumes:
  api-volume:

services:
  db:
    image: mariadb:10.3.6
    restart: always
    volumes:
      - ${STORAGE_PATH}/mariadb:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  elastic:
    image: elasticsearch:5
    restart: always

  api:
    image: deuxmax/concerto-api:latest
    restart: always
    env_file: .env.app.prod
    links:
      - db
      - elastic
    volumes:
      - ./Docker/php/www.prod.conf:/etc/php/7.1/fpm/pool.d/www.conf:ro
      - api-volume:/var/app

  nginx:
    image: nginx:1.13
    ports:
      - 8088:80
    links:
      - api
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/conf.d/site.prod.conf:/etc/nginx/conf.d/default.conf
      - api-volume:/var/app

  scrapper:
    image: deuxmax/concerto-scrapper:latest
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CONCERTO_URL: 'http://app/api'

  redis:
    image: redis:3.2
    volumes:
      - ${STORAGE_PATH}/redis:/data