#index:
#    path: /
#    controller: App\Controller\DefaultController::index
users:
  type: rest
  prefix: api
  resource: App\Controller\UserController

security:
  type: rest
  prefix: api/authenticate
  resource: App\Controller\SecurityController

artists:
  type: rest
  prefix: api
  resource: App\Controller\ArtistController

locations:
  type: rest
  prefix: api
  resource: App\Controller\LocationController

events:
  type: rest
  prefix: api
  resource: App\Controller\EventController

search:
  type: rest
  prefix: api
  resource: App\Controller\SearchController

scrap_search:
  type: rest
  prefix: scrap
  name_prefix: _scrap
  resource: App\Controller\SearchController