#index:
#    path: /
#    controller: App\Controller\DefaultController::index
users:
    type: rest
    prefix: api
    resource: App\Controller\UserController

security:
    type: rest
    prefix: api/authenticate
    resource: App\Controller\SecurityController

artists:
    type: rest
    prefix: api
    resource: App\Controller\ArtistController