<?php

namespace App\Tests\Utils;

use App\Entity\User;
use Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class CustomWebTestCase extends WebTestCase
{
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        static::bootKernel();
    }

    protected function login(User $user)
    {
        /** @var JWTManager $jwtManager */
        $jwtManager = self::get('lexik_jwt_authentication.jwt_manager');

        return $jwtManager->create($user);
    }

    protected function get($id)
    {
        $kernel = $this->createKernel([
            'environment' => 'test'
        ]);
        $kernel->boot();
        return $kernel->getContainer()->get($id);
    }

    protected function getCorrectEmail($prefix, $noRandom = null)
    {
        if (!$noRandom) {
            $noRandom = mt_rand();
        }
        $arEmail = explode('@', getenv('BASE_EMAIL_TO_SEND'));
        return $arEmail[0].'+'.$prefix.$noRandom.'@'.$arEmail[1];
    }
}